name: Docker Build and Push

# Trigger the workflow on push
on:
  push:
    paths:
      - 'ex2/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code (done automatically by actions/checkout)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using docker login
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator-app:${{ github.sha }} ./ex2

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/calculator-app:${{ github.sha }}
